apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  namespace: bitcoin-app-namespace
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:13
    env:
    - name: POSTGRES_USER
      value: "username"
    - name: POSTGRES_PASSWORD
      value: "password"
    - name: POSTGRES_DB
      value: "dbname"
    volumeMounts:
    - name: postgres-storage
      mountPath: /var/lib/postgresql/data
    ports:
    - containerPort: 5432
  volumes:
  - name: postgres-storage
    emptyDir: {}
